### ISSUE TITLE
Installed and started but with no clock, black terminal

### ISSUE THREAD

**Issue by Werror** [shaggytwodope/clockr#16]
I used the command you showed in the README, I do not know what I am doing it wrong.

**Comment by bdalenoord** [comment]
What version of clockr are you running? You can check with `clockr --version`

**Comment by Werror** [comment]
-> clockr --version
clockr 1.0

**Comment by bdalenoord** [comment]
That seems about right. I can reproduce the issue, but only when running 'clockr' after installation. If I run it uninstalled (`./clockr/clockr.py` from the directory where the sources were checked out) it seems to work fine.

I haven't worked on the installation scripts nor have I got any experience in using easy_install for Python, so I'm afraid I'll have to pass. @shaggytwodope have you got an idea?

**Comment by shaggytwodope** [comment]
What commands did you run exactly for install? And what distro did you run this on. At this time it's solely for python2. If you are on archlinux or any distro that's moved to python3 as default there may be issues.

If you ran `python setup.py install` try this with `python2` instead.

**Comment by Werror** [comment]
I used `python setup.py install`, and my system only have `python2.6` and `python2.7`

**Comment by Werror** [comment]
starting the program using `python  ./clockr/clockr.py` gives me 
`Traceback (most recent call last):
  File "clockr.py", line 12, in <module>
    from .__version__ import __version__
ValueError: Attempted relative import in non-package`

**Comment by shaggytwodope** [comment]
The relative import error is sorta an funky issue. Try just running `./clockr/clockr.py` in the dir. That aside, are you using tmux or anything? I've not tested well enough to know what issues could come up.

**Comment by DerVerruckteFuchs** [comment]
I'm having a similar issue. Just running `./clockr/clockr.py` gives me this output:

`Traceback (most recent call last):
  File "./clockr/clockr.py", line 11, in <module>
    from .__version__ import __version__
SystemError: Parent module '' not loaded, cannot perform relative import`

`python2 ./clockr/clockr.py` gives me:

`Traceback (most recent call last):
  File "./clockr/clockr.py", line 11, in <module>
    from .__version__ import __version__
ValueError: Attempted relative import in non-package`

So checking line 11 it has:

`from .__version__ import __version__`

Removing the leading period from the line, making it:

`from __version__ import __version__`

seems to fix it and clockr shows up like normal.

**Comment by shaggytwodope** [comment]
@DerVerruckteFuchs I'll look into this more when time permits. Just one thing to note, python2 will fail to run at this time. Never really took time to make sure it ran on python2. I may just have to remove the version thing... relative imports are troublesome.

**Comment by DerVerruckteFuchs** [comment]
I have both python 3.5 and 2.7 installed and have been using both to play with clockr, and can confirm that using python2 just gives a blank screen.

**Comment by DerVerruckteFuchs** [comment]
There was a big python update to version 3.6 for Arch and a fresh install of clockr runs just fine for me.
